[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = true

[tool.isort]
line_length = 120
force_single_line = true
lines_after_imports = 2

[tool.pylint.format]
max-line-length = '120'

[tool.pylint.similarities]
min-similarity-lines = '20'
ignore-imports = 'yes'

[tool.pylint.messages_control]
extension-pkg-whitelist = 'pydantic'
disable = '''
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    too-few-public-methods,
    invalid-name,
    import-outside-toplevel,
    redefined-outer-name,
    wrong-import-order,
    too-many-ancestors,
    too-many-arguments,
'''
